---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      nodeSelector:
        kubernetes.io/hostname: vps
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "vps"
          effect: "NoSchedule"
      containers:
        - name: focalboard
          image: mattermost/focalboard:7.11.4
          env:
            - name: VIRTUAL_HOST
              value: focalboard.local
            - name: VIRTUAL_PORT
              value: "8000"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data-volume
              mountPath: /opt/focalboard/data
              subPath: focalboard
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
