---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-ingress
  annotations:
    traefik.ingress.k8s.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  rules:
    - host: victoria.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoria-service
                port:
                  number: 8428
  tls:
    - hosts:
        - victoria.${DOMAIN}
      secretName: victoria-tls
