---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vesta
  - memos
  - myspeed
  - searxng
  - ntfy
  - n8n
  - wakapi
  - vaultwarden
  - jellyfin
  - metube
  - syncthing
  - miniserve
  - paperless-ngx
  - schedula
  # - adguard-home
  - commafeed
  - error-page
  - focalboard
  - grafana
  - prometheus
  - victoria-metrics
  - loki
  - alloy
