---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - data-pv.yaml
  - data-pvc.yaml
  - victoria-metrics-storage-class.yaml
  - victoria-metrics-local-pv.yaml
